spring.application.name=employee-asset-management
spring.datasource.url=jdbc:mysql://localhost:3306/employee_asset_management
spring.datasource.username=root
spring.datasource.password=Spring@5757

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true